language: golang
addons:
  ssh_known_hosts: microlog.co
script:
-
deploy:
- provider: script
  skip_cleanup: true
  script: ssh root@microlog.co "cd microlog-staging && bash scripts/deploy.sh"
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: ssh root@microlog.co "cd microlog && scripts/deploy.sh"
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_20c066664120_key -iv $encrypted_20c066664120_iv
  -in secrets/travis_rsa.enc -out $HOME/.ssh/travis_rsa -d
