version: '3.5'
services:
  session:
    build:
      context: .
      dockerfile: session/Dockerfile
    depends_on:
    - session_db
    env_file:
      - .env.prod
  session_db:
    image: redis
    volumes:
      - /data
    env_file:
      - .env.prod
    command: ["redis-server", "--requirepass", "$${SESSION_REDISPASSWORD}", "--appendonly", "yes"]
  mail:
    build:
      context: .
      dockerfile: mail/Dockerfile
    env_file:
      - .env.prod
  web_db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - .env.prod
  web:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    depends_on:
      - web_db
    restart: always
    ports:
      - "80:8080"
    volumes:
      - ./micro.db:/app/micro.db
    env_file:
      - .env.prod
