version: '3.5'
services:
  mail:
    build:
      context: .
      dockerfile: mail/Dockerfile
    ports:
    - "8080"
    env_file:
    - .env.prod
  web:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
    - "80:8080"
    volumes:
    - ./micro.db:/app/micro.db
    env_file:
    - .env.prod
