version: '3.5'
services:
  session:
    build:
      context: .
      dockerfile: session/Dockerfile
    depends_on:
    - session_db
    env_file: .env
    restart: always
  session_db:
    image: redis:alpine
    env_file: .env
    volumes:
      - "/data"
    command: ["sh", "-c", "exec redis-server --requirepass \"$$SESSION_REDISPASSWORD\""]
    restart: always
  mail:
    build:
      context: .
      dockerfile: mail/Dockerfile
    env_file: .env
    restart: always
  web_db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    env_file: .env
    restart: always
  web:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    depends_on:
      - web_db
    restart: always
    env_file: .env
