version: '3.5'
services:
  mail:
    build: mail/.
    ports:
    - "8080"
    env_file:
    - .env.prod
  web:
    build: gateway/.
    ports:
    - "80:8080"
    volumes:
    - ./micro.db:/app/micro.db
    env_file:
    - .env.prod
