version: '3.5'
services:
  web:
    build: .
    labels:
    - "traefik.frontend.rule=Host:microlog.co"
    ports:
    - '8080'
    volumes:
    - ./micro.db:/app/micro.db
    env_file:
    - prod.env
