// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	session.proto

It has these top-level messages:
	CreateRequest
	CreateResponse
	VerifyRequest
	VerifyResponse
	DeleteRequest
	DeleteResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRequest struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Role string `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type CreateResponse struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *VerifyRequest) Reset()                    { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string            { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()               {}
func (*VerifyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VerifyRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyResponse struct {
	Ok   bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Id   uint32 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Role string `protobuf:"bytes,3,opt,name=role" json:"role,omitempty"`
}

func (m *VerifyResponse) Reset()                    { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string            { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()               {}
func (*VerifyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *VerifyResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *VerifyResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VerifyResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type DeleteRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*CreateRequest)(nil), "api.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "api.CreateResponse")
	proto.RegisterType((*VerifyRequest)(nil), "api.VerifyRequest")
	proto.RegisterType((*VerifyResponse)(nil), "api.VerifyResponse")
	proto.RegisterType((*DeleteRequest)(nil), "api.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "api.DeleteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SessionService service

type SessionServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type sessionServiceClient struct {
	cc *grpc.ClientConn
}

func NewSessionServiceClient(cc *grpc.ClientConn) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/api.SessionService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := grpc.Invoke(ctx, "/api.SessionService/Verify", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/api.SessionService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SessionService service

type SessionServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterSessionServiceServer(s *grpc.Server, srv SessionServiceServer) {
	s.RegisterService(&_SessionService_serviceDesc, srv)
}

func _SessionService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SessionService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SessionService/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SessionService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SessionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SessionService_Create_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _SessionService_Verify_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SessionService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session.proto",
}

func init() { proto.RegisterFile("session.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xbb, 0xa9, 0x16, 0x3b, 0x90, 0x20, 0xa3, 0x87, 0xe2, 0xa9, 0x04, 0x2a, 0x3d, 0xed,
	0xc1, 0x7d, 0x04, 0xfb, 0x04, 0x29, 0x78, 0x5f, 0xed, 0x08, 0x61, 0xcb, 0xce, 0x9a, 0xac, 0x82,
	0x4f, 0xe5, 0x2b, 0x8a, 0x3b, 0x09, 0x1a, 0xdc, 0x5b, 0x12, 0xfe, 0xef, 0x9f, 0xff, 0x9f, 0x80,
	0x8e, 0x14, 0xa3, 0xe7, 0xbe, 0x1e, 0x02, 0x8f, 0x8c, 0xcb, 0x76, 0xf0, 0xb6, 0x01, 0xfd, 0x18,
	0xa8, 0x1d, 0xc9, 0xd1, 0xdb, 0x3b, 0xc5, 0x11, 0x0d, 0x28, 0x7f, 0xda, 0x54, 0xdb, 0x6a, 0xaf,
	0x9d, 0xf2, 0x27, 0x44, 0xb8, 0x08, 0x7c, 0xa6, 0x8d, 0xda, 0x56, 0xfb, 0xb5, 0x9b, 0xce, 0xf6,
	0x1e, 0x4c, 0x86, 0xe2, 0xc0, 0x7d, 0x24, 0xbc, 0x85, 0xcb, 0x91, 0x3b, 0xea, 0x27, 0x70, 0xed,
	0xe4, 0x62, 0x77, 0xa0, 0x9f, 0x28, 0xf8, 0xd7, 0xcf, 0x6c, 0x3e, 0x2f, 0x3b, 0x80, 0xc9, 0xb2,
	0x64, 0x67, 0x40, 0x71, 0x37, 0x89, 0xae, 0x9c, 0xe2, 0x2e, 0x85, 0x52, 0xff, 0x42, 0x2d, 0xff,
	0x84, 0xda, 0x81, 0x3e, 0xd0, 0x99, 0x7e, 0x9b, 0xcc, 0x0f, 0xbb, 0x06, 0x93, 0x65, 0x32, 0xec,
	0xe1, 0xab, 0x02, 0x73, 0x94, 0xcd, 0x1c, 0x29, 0x7c, 0xf8, 0x17, 0xc2, 0x06, 0x56, 0x52, 0x10,
	0xb1, 0x6e, 0x07, 0x5f, 0x17, 0x2b, 0xba, 0xbb, 0x29, 0xde, 0xc4, 0xc5, 0x2e, 0x7e, 0x20, 0xa9,
	0x91, 0xa0, 0xa2, 0x7a, 0x82, 0xca, 0x9e, 0x02, 0x49, 0x9c, 0x04, 0x15, 0x15, 0x12, 0x54, 0xe6,
	0xb5, 0x8b, 0xe7, 0xd5, 0xf4, 0x81, 0xcd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xeb, 0x2e,
	0x7a, 0xd1, 0x01, 0x00, 0x00,
}
