// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProfileCreateRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileCreateRequest) Reset()         { *m = ProfileCreateRequest{} }
func (m *ProfileCreateRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileCreateRequest) ProtoMessage()    {}
func (*ProfileCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

func (m *ProfileCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileCreateRequest.Unmarshal(m, b)
}
func (m *ProfileCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileCreateRequest.Marshal(b, m, deterministic)
}
func (m *ProfileCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileCreateRequest.Merge(m, src)
}
func (m *ProfileCreateRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileCreateRequest.Size(m)
}
func (m *ProfileCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileCreateRequest proto.InternalMessageInfo

func (m *ProfileCreateRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProfileCreateRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type ProfileCreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileCreateResponse) Reset()         { *m = ProfileCreateResponse{} }
func (m *ProfileCreateResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileCreateResponse) ProtoMessage()    {}
func (*ProfileCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{1}
}

func (m *ProfileCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileCreateResponse.Unmarshal(m, b)
}
func (m *ProfileCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileCreateResponse.Marshal(b, m, deterministic)
}
func (m *ProfileCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileCreateResponse.Merge(m, src)
}
func (m *ProfileCreateResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileCreateResponse.Size(m)
}
func (m *ProfileCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileCreateResponse proto.InternalMessageInfo

type ProfileDeleteRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileDeleteRequest) Reset()         { *m = ProfileDeleteRequest{} }
func (m *ProfileDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileDeleteRequest) ProtoMessage()    {}
func (*ProfileDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{2}
}

func (m *ProfileDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileDeleteRequest.Unmarshal(m, b)
}
func (m *ProfileDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileDeleteRequest.Marshal(b, m, deterministic)
}
func (m *ProfileDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileDeleteRequest.Merge(m, src)
}
func (m *ProfileDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileDeleteRequest.Size(m)
}
func (m *ProfileDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileDeleteRequest proto.InternalMessageInfo

func (m *ProfileDeleteRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ProfileDeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileDeleteResponse) Reset()         { *m = ProfileDeleteResponse{} }
func (m *ProfileDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileDeleteResponse) ProtoMessage()    {}
func (*ProfileDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{3}
}

func (m *ProfileDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileDeleteResponse.Unmarshal(m, b)
}
func (m *ProfileDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileDeleteResponse.Marshal(b, m, deterministic)
}
func (m *ProfileDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileDeleteResponse.Merge(m, src)
}
func (m *ProfileDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileDeleteResponse.Size(m)
}
func (m *ProfileDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileDeleteResponse proto.InternalMessageInfo

type ProfileGetRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileGetRequest) Reset()         { *m = ProfileGetRequest{} }
func (m *ProfileGetRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileGetRequest) ProtoMessage()    {}
func (*ProfileGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{4}
}

func (m *ProfileGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileGetRequest.Unmarshal(m, b)
}
func (m *ProfileGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileGetRequest.Marshal(b, m, deterministic)
}
func (m *ProfileGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileGetRequest.Merge(m, src)
}
func (m *ProfileGetRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileGetRequest.Size(m)
}
func (m *ProfileGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileGetRequest proto.InternalMessageInfo

func (m *ProfileGetRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ProfileUpdateRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Biography            string   `protobuf:"bytes,3,opt,name=biography,proto3" json:"biography,omitempty"`
	Image                []byte   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileUpdateRequest) Reset()         { *m = ProfileUpdateRequest{} }
func (m *ProfileUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileUpdateRequest) ProtoMessage()    {}
func (*ProfileUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{5}
}

func (m *ProfileUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileUpdateRequest.Unmarshal(m, b)
}
func (m *ProfileUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileUpdateRequest.Marshal(b, m, deterministic)
}
func (m *ProfileUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileUpdateRequest.Merge(m, src)
}
func (m *ProfileUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileUpdateRequest.Size(m)
}
func (m *ProfileUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileUpdateRequest proto.InternalMessageInfo

func (m *ProfileUpdateRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProfileUpdateRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ProfileUpdateRequest) GetBiography() string {
	if m != nil {
		return m.Biography
	}
	return ""
}

func (m *ProfileUpdateRequest) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type ProfileResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Biography            string   `protobuf:"bytes,3,opt,name=biography,proto3" json:"biography,omitempty"`
	ImageURL             string   `protobuf:"bytes,4,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileResponse) Reset()         { *m = ProfileResponse{} }
func (m *ProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileResponse) ProtoMessage()    {}
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{6}
}

func (m *ProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileResponse.Unmarshal(m, b)
}
func (m *ProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileResponse.Marshal(b, m, deterministic)
}
func (m *ProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileResponse.Merge(m, src)
}
func (m *ProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileResponse.Size(m)
}
func (m *ProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileResponse proto.InternalMessageInfo

func (m *ProfileResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProfileResponse) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ProfileResponse) GetBiography() string {
	if m != nil {
		return m.Biography
	}
	return ""
}

func (m *ProfileResponse) GetImageURL() string {
	if m != nil {
		return m.ImageURL
	}
	return ""
}

func init() {
	proto.RegisterType((*ProfileCreateRequest)(nil), "microlog.profile.v1.ProfileCreateRequest")
	proto.RegisterType((*ProfileCreateResponse)(nil), "microlog.profile.v1.ProfileCreateResponse")
	proto.RegisterType((*ProfileDeleteRequest)(nil), "microlog.profile.v1.ProfileDeleteRequest")
	proto.RegisterType((*ProfileDeleteResponse)(nil), "microlog.profile.v1.ProfileDeleteResponse")
	proto.RegisterType((*ProfileGetRequest)(nil), "microlog.profile.v1.ProfileGetRequest")
	proto.RegisterType((*ProfileUpdateRequest)(nil), "microlog.profile.v1.ProfileUpdateRequest")
	proto.RegisterType((*ProfileResponse)(nil), "microlog.profile.v1.ProfileResponse")
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor_744bf7a47b381504) }

var fileDescriptor_744bf7a47b381504 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xcf, 0x4a, 0xf3, 0x40,
	0x10, 0xc0, 0x9b, 0xfe, 0xfb, 0xbe, 0x4e, 0xad, 0xa5, 0x6b, 0xc5, 0x50, 0x3c, 0x84, 0x28, 0xa5,
	0x7a, 0x08, 0xa8, 0x6f, 0x50, 0x0b, 0x55, 0x10, 0x91, 0x85, 0x5c, 0x3c, 0xb9, 0x35, 0xd3, 0xb8,
	0x90, 0xb8, 0x6b, 0x12, 0x85, 0x82, 0xbe, 0xa6, 0xcf, 0x23, 0xcd, 0x26, 0x69, 0x5a, 0xda, 0x50,
	0xd0, 0x1e, 0x67, 0x76, 0x66, 0x7e, 0xd9, 0xfc, 0x86, 0x85, 0x96, 0x0c, 0xc4, 0x94, 0x7b, 0x68,
	0xc9, 0x40, 0x44, 0x82, 0x1c, 0xf8, 0xfc, 0x39, 0x10, 0x9e, 0x70, 0xad, 0x34, 0xff, 0x71, 0x61,
	0xde, 0x40, 0xf7, 0x41, 0x45, 0xd7, 0x01, 0xb2, 0x08, 0x29, 0xbe, 0xbd, 0x63, 0x18, 0x91, 0x7d,
	0x28, 0x73, 0x47, 0xd7, 0x0c, 0x6d, 0xd0, 0xa2, 0x65, 0xee, 0x10, 0x03, 0x9a, 0x0e, 0x0f, 0xa5,
	0xc7, 0x66, 0xf7, 0xcc, 0x47, 0xbd, 0x6c, 0x68, 0x83, 0x06, 0xcd, 0xa7, 0xcc, 0x23, 0x38, 0x5c,
	0x99, 0x14, 0x4a, 0xf1, 0x1a, 0xa2, 0xd9, 0xcf, 0x10, 0x23, 0xf4, 0x70, 0x23, 0x22, 0x37, 0x20,
	0xad, 0x4b, 0x06, 0x9c, 0x40, 0x27, 0x39, 0x18, 0x63, 0xb4, 0xa9, 0xfb, 0x33, 0xa3, 0xd8, 0xd2,
	0xf9, 0xcd, 0x45, 0xc8, 0x31, 0x34, 0x26, 0x5c, 0xb8, 0x01, 0x93, 0x2f, 0x33, 0xbd, 0x12, 0x9f,
	0x2f, 0x12, 0xa4, 0x0b, 0x35, 0xee, 0x33, 0x17, 0xf5, 0xaa, 0xa1, 0x0d, 0xf6, 0xa8, 0x0a, 0xcc,
	0x2f, 0x68, 0x27, 0xf4, 0xf4, 0xab, 0xff, 0x1c, 0xdc, 0x83, 0xff, 0x31, 0xcb, 0xa6, 0x77, 0x31,
	0xbb, 0x41, 0xb3, 0xf8, 0xf2, 0xbb, 0x0a, 0xff, 0x12, 0x3e, 0x61, 0x50, 0x57, 0x02, 0xc8, 0x99,
	0xb5, 0xc6, 0xb8, 0xb5, 0x4e, 0x77, 0xef, 0x7c, 0x9b, 0xd2, 0x44, 0x47, 0x69, 0x8e, 0x50, 0x8a,
	0x8a, 0x11, 0x4b, 0xba, 0x8b, 0x11, 0x2b, 0xc6, 0x4b, 0xc4, 0x86, 0xca, 0x18, 0x23, 0xd2, 0x2f,
	0x6a, 0x5a, 0x6c, 0x43, 0xef, 0xb4, 0xa8, 0x2e, 0x37, 0x76, 0x0a, 0x1d, 0xb5, 0x1e, 0xa3, 0xdc,
	0x7f, 0x2f, 0xbc, 0xc4, 0xd2, 0x36, 0x6d, 0xcd, 0x71, 0xa0, 0xad, 0x1a, 0x87, 0x99, 0xbf, 0x1d,
	0x50, 0x9e, 0xa0, 0xa9, 0x1a, 0x6f, 0xe7, 0x8b, 0xb0, 0x03, 0xc2, 0xb0, 0xf6, 0x58, 0x61, 0x92,
	0x4f, 0xea, 0xf1, 0x0b, 0x72, 0xf5, 0x13, 0x00, 0x00, 0xff, 0xff, 0x24, 0xf6, 0xa0, 0xb9, 0x52,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfileClient is the client API for Profile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileClient interface {
	Create(ctx context.Context, in *ProfileCreateRequest, opts ...grpc.CallOption) (*ProfileCreateResponse, error)
	Delete(ctx context.Context, in *ProfileDeleteRequest, opts ...grpc.CallOption) (*ProfileDeleteResponse, error)
	Get(ctx context.Context, in *ProfileGetRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	UpdateDisplayName(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	UpdateBiography(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	UpdateImage(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
}

type profileClient struct {
	cc *grpc.ClientConn
}

func NewProfileClient(cc *grpc.ClientConn) ProfileClient {
	return &profileClient{cc}
}

func (c *profileClient) Create(ctx context.Context, in *ProfileCreateRequest, opts ...grpc.CallOption) (*ProfileCreateResponse, error) {
	out := new(ProfileCreateResponse)
	err := c.cc.Invoke(ctx, "/microlog.profile.v1.Profile/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) Delete(ctx context.Context, in *ProfileDeleteRequest, opts ...grpc.CallOption) (*ProfileDeleteResponse, error) {
	out := new(ProfileDeleteResponse)
	err := c.cc.Invoke(ctx, "/microlog.profile.v1.Profile/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) Get(ctx context.Context, in *ProfileGetRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/microlog.profile.v1.Profile/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) UpdateDisplayName(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/microlog.profile.v1.Profile/UpdateDisplayName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) UpdateBiography(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/microlog.profile.v1.Profile/UpdateBiography", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) UpdateImage(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/microlog.profile.v1.Profile/UpdateImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServer is the server API for Profile service.
type ProfileServer interface {
	Create(context.Context, *ProfileCreateRequest) (*ProfileCreateResponse, error)
	Delete(context.Context, *ProfileDeleteRequest) (*ProfileDeleteResponse, error)
	Get(context.Context, *ProfileGetRequest) (*ProfileResponse, error)
	UpdateDisplayName(context.Context, *ProfileUpdateRequest) (*ProfileResponse, error)
	UpdateBiography(context.Context, *ProfileUpdateRequest) (*ProfileResponse, error)
	UpdateImage(context.Context, *ProfileUpdateRequest) (*ProfileResponse, error)
}

// UnimplementedProfileServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServer struct {
}

func (*UnimplementedProfileServer) Create(ctx context.Context, req *ProfileCreateRequest) (*ProfileCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedProfileServer) Delete(ctx context.Context, req *ProfileDeleteRequest) (*ProfileDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedProfileServer) Get(ctx context.Context, req *ProfileGetRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedProfileServer) UpdateDisplayName(ctx context.Context, req *ProfileUpdateRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDisplayName not implemented")
}
func (*UnimplementedProfileServer) UpdateBiography(ctx context.Context, req *ProfileUpdateRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBiography not implemented")
}
func (*UnimplementedProfileServer) UpdateImage(ctx context.Context, req *ProfileUpdateRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateImage not implemented")
}

func RegisterProfileServer(s *grpc.Server, srv ProfileServer) {
	s.RegisterService(&_Profile_serviceDesc, srv)
}

func _Profile_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microlog.profile.v1.Profile/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).Create(ctx, req.(*ProfileCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microlog.profile.v1.Profile/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).Delete(ctx, req.(*ProfileDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microlog.profile.v1.Profile/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).Get(ctx, req.(*ProfileGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_UpdateDisplayName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).UpdateDisplayName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microlog.profile.v1.Profile/UpdateDisplayName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).UpdateDisplayName(ctx, req.(*ProfileUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_UpdateBiography_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).UpdateBiography(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microlog.profile.v1.Profile/UpdateBiography",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).UpdateBiography(ctx, req.(*ProfileUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_UpdateImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).UpdateImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microlog.profile.v1.Profile/UpdateImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).UpdateImage(ctx, req.(*ProfileUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Profile_serviceDesc = grpc.ServiceDesc{
	ServiceName: "microlog.profile.v1.Profile",
	HandlerType: (*ProfileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Profile_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Profile_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Profile_Get_Handler,
		},
		{
			MethodName: "UpdateDisplayName",
			Handler:    _Profile_UpdateDisplayName_Handler,
		},
		{
			MethodName: "UpdateBiography",
			Handler:    _Profile_UpdateBiography_Handler,
		},
		{
			MethodName: "UpdateImage",
			Handler:    _Profile_UpdateImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile.proto",
}
